services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bank_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - java_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  wildfly:
    image: quay.io/wildfly/wildfly:latest
    container_name: wildfly
    restart: always
    networks:
      - java_app
    ports:
      - "8080:8080" # Application
      - "9990:9990" # Admin console
    volumes:
      - ./Wildfly:/opt/jboss/wildfly
    command:
      ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-full.xml"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - java_app
    ports:
      - 8081:80
    depends_on:
      - db

volumes:
  db_data:

networks:
  java_app:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
