services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bank_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - java_app
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - java_app
    ports:
      - 8081:80
    depends_on:
      - db

networks:
  java_app:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
